insert into public.matches(stage, match_no, kickoff_utc, home, away, final_home, final_away, is_finished)
values
  ('Alagrupiturniir',1,NULL,'Mexico','South Africa',NULL,NULL,false),
  ('Alagrupiturniir',2,NULL,'South Korea','Czechia',NULL,NULL,false),
  ('Alagrupiturniir',3,NULL,'Canada','Bosnia and Herzegovina',NULL,NULL,false),
  ('Alagrupiturniir',4,NULL,'USA','Paraguay',NULL,NULL,false),
  ('Alagrupiturniir',5,NULL,'Qatar','Switzerland',NULL,NULL,false),
  ('Alagrupiturniir',6,NULL,'Brazil','Morocco',NULL,NULL,false),
  ('Alagrupiturniir',7,NULL,'Haiti','Scotland',NULL,NULL,false),
  ('Alagrupiturniir',8,NULL,'Australia','Türkiye',NULL,NULL,false),
  ('Alagrupiturniir',9,NULL,'Germany','Curaçao',NULL,NULL,false),
  ('Alagrupiturniir',10,NULL,'Netherlands','Japan',NULL,NULL,false),
  ('Alagrupiturniir',11,NULL,'Ivory Coast','Ecuador',NULL,NULL,false),
  ('Alagrupiturniir',12,NULL,'Tunisia','Sweden',NULL,NULL,false),
  ('Alagrupiturniir',13,NULL,'Spain','Cape Verde',NULL,NULL,false),
  ('Alagrupiturniir',14,NULL,'Belgium','Egypt',NULL,NULL,false),
  ('Alagrupiturniir',15,NULL,'Saudi Arabia','Uruguay',NULL,NULL,false),
  ('Alagrupiturniir',16,NULL,'Iran','New Zealand',NULL,NULL,false),
  ('Alagrupiturniir',17,NULL,'France','Senegal',NULL,NULL,false),
  ('Alagrupiturniir',18,NULL,'Iraq','Norway',NULL,NULL,false),
  ('Alagrupiturniir',19,NULL,'Argentina','Algeria',NULL,NULL,false),
  ('Alagrupiturniir',20,NULL,'Austria','Jordan',NULL,NULL,false),
  ('Alagrupiturniir',21,NULL,'Portugal','Congo DR',NULL,NULL,false),
  ('Alagrupiturniir',22,NULL,'England','Croatia',NULL,NULL,false),
  ('Alagrupiturniir',23,NULL,'Ghana','Panama',NULL,NULL,false),
  ('Alagrupiturniir',24,NULL,'Uzbekistan','Colombia',NULL,NULL,false),
  ('Alagrupiturniir',25,NULL,'Czechia','South Africa',NULL,NULL,false),
  ('Alagrupiturniir',26,NULL,'Switzerland','Bosnia and Herzegovina',NULL,NULL,false),
  ('Alagrupiturniir',27,NULL,'Canada','Qatar',NULL,NULL,false),
  ('Alagrupiturniir',28,NULL,'Mexico','South Korea',NULL,NULL,false),
  ('Alagrupiturniir',29,NULL,'USA','Australia',NULL,NULL,false),
  ('Alagrupiturniir',30,NULL,'Scotland','Morocco',NULL,NULL,false),
  ('Alagrupiturniir',31,NULL,'Brazil','Haiti',NULL,NULL,false),
  ('Alagrupiturniir',32,NULL,'Türkiye','Paraguay',NULL,NULL,false),
  ('Alagrupiturniir',33,NULL,'Netherlands','Sweden',NULL,NULL,false),
  ('Alagrupiturniir',34,NULL,'Germany','Ivory Coast',NULL,NULL,false),
  ('Alagrupiturniir',35,NULL,'Ecuador','Curaçao',NULL,NULL,false),
  ('Alagrupiturniir',36,NULL,'Tunisia','Japan',NULL,NULL,false),
  ('Alagrupiturniir',37,NULL,'Spain','Saudi Arabia',NULL,NULL,false),
  ('Alagrupiturniir',38,NULL,'Belgium','Iran',NULL,NULL,false),
  ('Alagrupiturniir',39,NULL,'Uruguay','Cape Verde',NULL,NULL,false),
  ('Alagrupiturniir',40,NULL,'New Zealand','Egypt',NULL,NULL,false),
  ('Alagrupiturniir',41,NULL,'Argentina','Austria',NULL,NULL,false),
  ('Alagrupiturniir',42,NULL,'France','Iraq',NULL,NULL,false),
  ('Alagrupiturniir',43,NULL,'Norway','Senegal',NULL,NULL,false),
  ('Alagrupiturniir',44,NULL,'Jordan','Algeria',NULL,NULL,false),
  ('Alagrupiturniir',45,NULL,'Portugal','Uzbekistan',NULL,NULL,false),
  ('Alagrupiturniir',46,NULL,'England','Ghana',NULL,NULL,false),
  ('Alagrupiturniir',47,NULL,'Panama','Croatia',NULL,NULL,false),
  ('Alagrupiturniir',48,NULL,'Colombia','Congo DR',NULL,NULL,false),
  ('Alagrupiturniir',49,NULL,'Switzerland','Canada',NULL,NULL,false),
  ('Alagrupiturniir',50,NULL,'Bosnia and Herzegovina','Qatar',NULL,NULL,false),
  ('Alagrupiturniir',51,NULL,'Brazil','Scotland',NULL,NULL,false),
  ('Alagrupiturniir',52,NULL,'Morocco','Haiti',NULL,NULL,false),
  ('Alagrupiturniir',53,NULL,'Mexico','Czechia',NULL,NULL,false),
  ('Alagrupiturniir',54,NULL,'South Korea','South Africa',NULL,NULL,false),
  ('Alagrupiturniir',55,NULL,'Ecuador','Germany',NULL,NULL,false),
  ('Alagrupiturniir',56,NULL,'Curaçao','Ivory Coast',NULL,NULL,false),
  ('Alagrupiturniir',57,NULL,'Tunisia','Netherlands',NULL,NULL,false),
  ('Alagrupiturniir',58,NULL,'Japan','Sweden',NULL,NULL,false),
  ('Alagrupiturniir',59,NULL,'USA','Türkiye',NULL,NULL,false),
  ('Alagrupiturniir',60,NULL,'Paraguay','Australia',NULL,NULL,false),
  ('Alagrupiturniir',61,NULL,'Norway','France',NULL,NULL,false),
  ('Alagrupiturniir',62,NULL,'Senegal','Iraq',NULL,NULL,false),
  ('Alagrupiturniir',63,NULL,'Uruguay','Spain',NULL,NULL,false),
  ('Alagrupiturniir',64,NULL,'Cape Verde','Saudi Arabia',NULL,NULL,false),
  ('Alagrupiturniir',65,NULL,'New Zealand','Belgium',NULL,NULL,false),
  ('Alagrupiturniir',66,NULL,'Egypt','Iran',NULL,NULL,false),
  ('Alagrupiturniir',67,NULL,'Panama','England',NULL,NULL,false),
  ('Alagrupiturniir',68,NULL,'Croatia','Ghana',NULL,NULL,false),
  ('Alagrupiturniir',69,NULL,'Colombia','Portugal',NULL,NULL,false),
  ('Alagrupiturniir',70,NULL,'Congo DR','Uzbekistan',NULL,NULL,false),
  ('Alagrupiturniir',71,NULL,'Argentina','Jordan',NULL,NULL,false),
  ('Alagrupiturniir',72,NULL,'Algeria','Austria',NULL,NULL,false),
  ('Round of 32',73,NULL,'2A','2B',NULL,NULL,false),
  ('Round of 32',74,NULL,'1C','2F',NULL,NULL,false),
  ('Round of 32',75,NULL,'1E','3A/B/C/D/F',NULL,NULL,false),
  ('Round of 32',76,NULL,'1F','2C',NULL,NULL,false),
  ('Round of 32',77,NULL,'2E','2I',NULL,NULL,false),
  ('Round of 32',78,NULL,'1I','3C/D/F/G/H',NULL,NULL,false),
  ('Round of 32',79,NULL,'1A','3C/E/F/H/I',NULL,NULL,false),
  ('Round of 32',80,NULL,'1L','3E/H/I/J/K',NULL,NULL,false),
  ('Round of 32',81,NULL,'1G','3A/E/H/I/J',NULL,NULL,false),
  ('Round of 32',82,NULL,'1D','3B/E/F/I/J',NULL,NULL,false),
  ('Round of 32',83,NULL,'1H','2J',NULL,NULL,false),
  ('Round of 32',84,NULL,'2K','2L',NULL,NULL,false),
  ('Round of 32',85,NULL,'1B','3D/E/I/J/L',NULL,NULL,false),
  ('Round of 32',86,NULL,'2D','2G',NULL,NULL,false),
  ('Round of 32',87,NULL,'1J','2H',NULL,NULL,false),
  ('Round of 32',88,NULL,'1K','3D/E/I/J/L',NULL,NULL,false),
  ('Kaheksandikfinaal',89,NULL,'TBD','TBD',NULL,NULL,false),
  ('Kaheksandikfinaal',90,NULL,'TBD','TBD',NULL,NULL,false),
  ('Kaheksandikfinaal',91,NULL,'TBD','TBD',NULL,NULL,false),
  ('Kaheksandikfinaal',92,NULL,'TBD','TBD',NULL,NULL,false),
  ('Kaheksandikfinaal',93,NULL,'TBD','TBD',NULL,NULL,false),
  ('Kaheksandikfinaal',94,NULL,'TBD','TBD',NULL,NULL,false),
  ('Kaheksandikfinaal',95,NULL,'TBD','TBD',NULL,NULL,false),
  ('Kaheksandikfinaal',96,NULL,'TBD','TBD',NULL,NULL,false),
  ('Veerandfinaal',97,NULL,'TBD','TBD',NULL,NULL,false),
  ('Veerandfinaal',98,NULL,'TBD','TBD',NULL,NULL,false),
  ('Veerandfinaal',99,NULL,'TBD','TBD',NULL,NULL,false),
  ('Veerandfinaal',100,NULL,'TBD','TBD',NULL,NULL,false),
  ('Poolfinaal',101,NULL,'TBD','TBD',NULL,NULL,false),
  ('Poolfinaal',102,NULL,'TBD','TBD',NULL,NULL,false),
  ('3. koha mäng',103,NULL,'TBD','TBD',NULL,NULL,false),
  ('Finaal',104,NULL,'TBD','TBD',NULL,NULL,false)
on conflict (match_no) do nothing;
