alter table public.matches
  add column if not exists went_extra boolean not null default false,
  add column if not exists status_short text,
  add column if not exists advancing_team text,
  add column if not exists api_football_fixture_id bigint;

alter table public.predictions
  add column if not exists advancing_team text;

create table if not exists public.app_settings (
  key text primary key,
  value text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.bonus_questions (
  id bigint generated by default as identity primary key,
  question_text text not null,
  answer_type text not null default 'text',
  options_source text not null default 'text',
  correct_answer_value text,
  correct_answer_text text,
  points int not null default 1,
  is_locked boolean not null default false,
  sort_order int not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bonus_answers (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  question_id bigint not null references public.bonus_questions(id) on delete cascade,
  answer_value text not null default '',
  answer_text text not null default '',
  is_correct boolean not null default false,
  points int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (player_id, question_id)
);

create index if not exists bonus_answers_player_id_idx on public.bonus_answers(player_id);
create index if not exists bonus_answers_question_id_idx on public.bonus_answers(question_id);

drop trigger if exists trg_app_settings_updated on public.app_settings;
create trigger trg_app_settings_updated before update on public.app_settings
for each row execute function public.set_updated_at();

drop trigger if exists trg_bonus_questions_updated on public.bonus_questions;
create trigger trg_bonus_questions_updated before update on public.bonus_questions
for each row execute function public.set_updated_at();

drop trigger if exists trg_bonus_answers_updated on public.bonus_answers;
create trigger trg_bonus_answers_updated before update on public.bonus_answers
for each row execute function public.set_updated_at();

insert into public.bonus_questions (question_text, answer_type, options_source, points, sort_order)
values
  ('Milline koondis tuleb maailmameistriks?', 'team', 'teams', 1, 1),
  ('Kes on turniiri suurim väravakütt?', 'player', 'players', 1, 2),
  ('Mitu väravat lööb oma viimasel suurturniiril Messi?', 'number', '0_20', 1, 3),
  ('Mitu väravat lööb oma viimasel suurturniiril Ronaldo?', 'number', '0_20', 1, 4),
  ('Kes võidab meie alagrupiturniiri ennustuse?', 'registered_user', 'registered_users', 1, 5),
  ('Kes jääb meie alagrupiturniiri ennustuses viimaseks?', 'registered_user', 'registered_users', 1, 6)
on conflict do nothing;

insert into public.app_settings (key, value)
values ('rules_text', 'Samsung JalkaMM 2026 ennustuses ennustad iga mängu 90 minuti skoori. Ennustus lukustub 1 tund enne mängu algust. Kui mäng on lukus, muutuvad teiste mängijate ennustused nähtavaks.

Punktid: õige võitja või õige viik annab 2 punkti. Õige kodutiimi väravate arv annab 1 punkti. Õige võõrsiltiimi väravate arv annab 1 punkti. Täpne skoor annab kokku 4 punkti.

Play-offides arvestatakse samuti 90 minuti skoori. Kui mäng läheb lisaajale või penaltitele, saab kasutaja 1 lisapunkti juhul, kui tema ennustusest tulenev edasipääseja on õige. Kui play-off mäng lõpeb 90 minutiga, edasipääseja eest lisapunkti ei anta.

Edetabelis on kaks arvestust: alagrupimängude edetabel ja play-off edetabel. Play-off algab nullist ning alagrupi punktid sinna üle ei tule. Lisaküsimuste punktid lisatakse play-off edetabelisse.

Lisaküsimustele saab vastata eraldi vaates. Admin määrab õiged vastused ja saab vajadusel vastuseid käsitsi õigeks või valeks märkida.')
on conflict (key) do nothing;
